### ISSUE TITLE
Birthday Notification

### ISSUE THREAD

**Issue by decoded-cipher** [decoded-cipher/cowin-bot#16]
Post a notification about the birthdays (today & tomorrow) in the `#inobot` channel, so that no one's birthdays be left unnoticed.
- Post as an embed message with the **Full Name**, **Discord ID** & **Birthday**.
- Check whether the user has a profile pic o not.
  - If `YES`, provide a recommended command so that the admin could copy-paste & execute it _(Embed with GREEN)_.
  - If `NO`, mark it as not recommended to run the command as User Pic is missing _(Embedd with RED)_.

**Comment by decoded-cipher** [comment]
![image](https://user-images.githubusercontent.com/44474792/166591140-9a857243-9adc-447c-80bb-13e45e94630c.png)
![image](https://user-images.githubusercontent.com/44474792/166591173-07e3428b-c4c4-451f-a353-94be3a311f04.png)

**Comment by decoded-cipher** [comment]
Still has an issue with **UTC to IST** conversion...

**Comment by decoded-cipher** [comment]
Post the birthday notification at a fixed time. For example, ```post the notification at sharp 12:05 AM everyday```, if someone is celebrating the birthday.

The idea to getting notified just because of the restart policy of Heroku is not ideal, as we might migrate to a better reliable Cloud Server in the future.

And, now a days, restart of Heroku Server is usually around 11-12 at night, which is not ideal.

**Comment by Jeevan1310** [comment]
## Need to resolve the glitch in birthday notification 

Cause : Now the bot is only posting birthday notification when we uses the birthday command ( $bday )**

We need the bot to trigger the bday notification exactly at 12:00 am  and must post all possible birthday info in the channel.
